export const routes = {
    Home: 'Home',
    Login: 'Login',
    VerifyEmail: 'Onboarding/Verify Email',
    ProfileSetup: 'Onboarding/Personal Details',
    AddressScreen: 'Onboarding/Address',
    Success: 'Onboarding/Success',
    Dashboard: 'Dashboard',
    Investment: 'Investment/StartInvesting',
    SettingsHome: "Settings/Home",
    Settings: 'Settings',
    SettingsMyDetails: 'Settings/My Details',
    LinkedAccounts: 'Settings/Linked Accounts',
    SettingsSecurity: 'Settings/Security',
    SettingsTfn: 'Settings/Tfn',
    FirstTimeInvestment: 'FirstTimeInvestment',
    TfnScreen: 'FirstTimeInvestment/Tfn',
    IdentityVerification: 'FirstTimeInvestment/Identity Verification',
    ChooseId: 'FirstTimeInvestment/Choose ID',
    PassportDetail: 'FirstTimeInvestment/PassportDetails',
    ConfirmResidence: 'FirstTimeInvestment/PassportDetails/Confirm Residence',
    ConfirmName: 'FirstTimeInvestment/PassportDetails/Confirm Name',
    ConfirmDate: 'FirstTimeInvestment/PassportDetails/Confirm DOB',
    ConfirmDetail: 'FirstTimeInvestment/PassportDetails/Confirm Details',
    DriverLicenceDetail: 'FirstTimeInvestment/DriversLicence/Details',
    DLConfirmName: 'FirstTimeInvestment/DriversLicence/Confirm Name',
    DLConfirmDate: 'FirstTimeInvestment/DriversLicence/Confirm DOB',
    DLConfirmResidence: 'FirstTimeInvestment/DriversLicence/Confirm Address',
    ConfirmDL: 'FirstTimeInvestment/DriversLicence/Confirm',
    SuccessPage: 'FirstTimeInvestment/IdentityVerification/Success',
    IdentityVerifyFailScreen:'FirstTimeInvestment/IdentityVerification/Fail',
    Portfolio: 'FirstTimeInvestment/Portfolio',
    AccountDetails: 'FirstTimeInvestment/AccountDetails',
    ConfirmAccountDetails: 'FirstTimeInvestment/AccountDetails/Confirm',
    InvestForm: 'FirstTimeInvestment/Investment',
    InvestSuccessScreen: 'FirstTimeInvestment/Investment/Success',
    TransactionHome: 'TransactionsHome',
    Transactions: 'Transactions',
    Summary: 'Transactions/Summary',
    History: 'Transactions/History',
    Withdrawals: 'Transactions/Withdrawals',
    WithdrawFunds: 'Transactions/WithdrawFunds',
    WithdrawalSuccessScreen: 'Transactions/WithdrawFunds/Success',
    RepeatInvest: 'Investments/RepeatInvestment',
    RepeatInvestSuccess: 'Investments/RepeatInvestment/Success',
    PortfolioOverview: 'Portfolio/Overview',
    InvestmentIndex: 'FirstTimeInvestment/StartInvesting',
    EverestPortfolio: 'Portfolio/Everest',
    PortfolioIndexPage: 'Portfolio/StartInvesting',
    TransactionIndexPage: 'Transactions/StartInvesting',
    ShareTaxInfoPage: 'FirstTimeInvestment/ShareTaxInfo',
    ContactSupportTeam: 'FirstTimeInvestment/ContactSupportTeam',
    Company: 'Portfolio/Company',
    IdentityVerifyHardStopScreen:'FirstTimeInvestment/IdentityVerification/HardStop',
};